name: ghuyom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.1.1
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  encrypt: ^5.0.1
  tuple: ^2.0.1
  crypto: ^3.0.2
  cached_network_image: ^3.2.3
  firebase_auth: ^4.4.0
  stacked_firebase_auth: ^2.19.2
  firebase_core: ^2.9.0
  flutter_otp_text_field: ^1.1.1
  persistent_bottom_nav_bar: ^5.0.2
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_typeahead: ^4.6.2
  image_picker: ^0.8.9
  url_launcher: ^6.1.12
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_paypal: ^0.2.0





dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/images/app_icon.png"
   min_sdk_android: 21 # android min sdk min:16, default 21
   adaptive_icon_background: "#ffffff"
   background_color_ios: "#ffffff"
   remove_alpha_ios: true


flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset : assets/fonts/Manrope-Regular.ttf
          weight : 400
        - asset : assets/fonts/Manrope-Medium.ttf
          weight : 500
        - asset : assets/fonts/Manrope-SemiBold.ttf
          weight : 600
        - asset : assets/fonts/Manrope-Bold.ttf
          weight : 700
        - asset : assets/fonts/Manrope-ExtraBold.ttf
          weight : 800

